### ISSUE TITLE
Horizontal line in active tab

### ISSUE THREAD

**Issue by Klaudioz** [Railly/one-hunter-vscode#40]
I'd like to have one, like the theme Dark+ v2 theme

![image](https://user-images.githubusercontent.com/632625/231471958-aa62bd6b-4aac-47fc-96a8-01f978536b10.png)

I really love this theme (The Vercel one) but it's difficult to me to find the active tab having several columns of them open.

Thanks.

**Comment by Railly** [comment]
Hi @Klaudioz, TIL that you can wrap your tabs 😂. 

![image](https://user-images.githubusercontent.com/51397083/232173596-e3f0f4b7-5859-4acc-89dd-9b38a4fe7d03.png)

Let me know if I'm right or not. So you expect to highlight both the text and the background color of an active tab, right? 

PD: The screenshot is just to show how looks right now.

**Comment by Klaudioz** [comment]
It looks great !!. How can I update it?

**Comment by Railly** [comment]
I didn't modify anything at all. It's the actual version, maybe I can make this active tab grayer. For now, you can go `Extensions `> `One Hunter Theme`  > Expand the options of `Uninstall`, and you can check the available versions.

![image](https://user-images.githubusercontent.com/51397083/232175734-e953f13c-8e12-4541-a561-420f67e3a2b4.png)

**Comment by Klaudioz** [comment]
I've current and I can't see it

<img width="340" alt="image" src="https://user-images.githubusercontent.com/632625/232176091-a4760205-c781-4e1b-bfb5-5a234ace7332.png">

I restarted VScode and I can't see it.

**Comment by Railly** [comment]
I guess you have this setting enabled, right?

![image](https://user-images.githubusercontent.com/51397083/232176193-3ecc19eb-7e4b-43bf-a4bd-fe36be15ff06.png)

**Comment by Klaudioz** [comment]
After activing it, I got everything with a bar 😁

<img width="651" alt="image" src="https://user-images.githubusercontent.com/632625/232177827-23134151-fd1f-4472-b930-0d87347eaa18.png">
