### ISSUE TITLE
Space and Tab symbols color is too light

### ISSUE THREAD

**Issue by levinhtin** [Railly/one-hunter-vscode#52]
I'm using light theme, space and tab symbols color is too light. It should be a little bit darker.

<img width="130" alt="image" src="https://github.com/Railly/one-hunter-vscode/assets/11834124/d51b888a-5abe-48a9-b473-e3e4c0de9e16">

**Comment by Railly** [comment]
Great, will be part of the next patches. Thank you

**Comment by Railly** [comment]
I make them darker but only for this variants for now. Which theme are you using?

![image](https://github.com/Railly/one-hunter-vscode/assets/51397083/262f365e-aa65-4341-9fe3-b60e128aca9f)
