### ISSUE TITLE
Cannot distinguish "occurrences highlight" from selection

### ISSUE THREAD

**Issue by awmottaz** [Railly/one-hunter-vscode#56]
I have the `editor.occurrencesHighlight` setting enabled in VSCode. When I click on a symbol, it is highlighted. If I then selected some text within the symbol, I cannot tell where that selection is because it has the same background as the occurrences highlight.

Here is how it looks with One Hunter Flexoki Light. The characters `oob` are selected, but you can't tell.

<img width="93" alt="Screenshot 2023-10-23 at 09 33 58" src="https://github.com/Railly/one-hunter-vscode/assets/17735385/c26d1308-f7a0-46f4-9468-db1421851780">

For comparison, the VSCode Light Modern theme properly distinguishes these two states:

<img width="108" alt="Screenshot 2023-10-23 at 09 33 02" src="https://github.com/Railly/one-hunter-vscode/assets/17735385/2f980d53-2e29-4c55-935a-78b9e69ad973">

**Comment by ltsuda** [comment]
I'm sorry if it's a different issue but seems very similar to what I see on my setup.

I'm using the Dark theme and the occurrence highlight colour is a bit hard to identify looking at display and overall code. Looking at this screenshot section only looks OK but on a daily bases with more code in the file, looks a bit harder. Appreciated the theme :)

![image](https://github.com/Railly/one-hunter-vscode/assets/3965277/9da8b147-bca6-4b42-8a02-a20ac3c38dfe)

**Comment by Railly** [comment]
I've just updated these 5 variants. I reduced the size from 999 lines to 548. Give it a try, and let me know if the issue persists.

![image](https://github.com/Railly/one-hunter-vscode/assets/51397083/38caf500-34f3-43dd-8c62-9c2737f7034c)

**Comment by Railly** [comment]
Thanks @ltsuda, I'll close this issue as completed!
Btw, tysm for the donation, I really appreciate it!🚀.
