### ISSUE TITLE
Consider publishing to Open VSX

### ISSUE THREAD

**Issue by yeskunall** [Railly/one-hunter-vscode#65]
Would you consider publishing this extension to [Open VSX](https://open-vsx.org/)? The instructions are [here](https://github.com/EclipseFdn/open-vsx.org/wiki/Publishing-Extensions).

---
Thanks for working on this theme. The Vercel variant is dope! 💖

**Comment by Railly** [comment]
Already done, thank you for bringing this up 💯

https://open-vsx.org/extension/RaillyHugo/one-hunter
